# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='longitude',
        ),
    ]
