# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='zip_code',
            field=models.TextField(default='00000-000', help_text='Cep vem aqui.'),
        ),
    ]
