# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-03 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171102_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='latitude',
            field=models.FloatField(default=-22.912194),
        ),
        migrations.AddField(
            model_name='realestate',
            name='longitude',
            field=models.FloatField(default=-43.24991),
        ),
    ]
