# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-03 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171103_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
